# Makefile

TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(shell pwd)/DotProduct.v
SIM = icarus
TOPLEVEL = DotProduct
MODULE = test_dot_product
GUI = 0
include $(shell cocotb-config --makefiles)/Makefile.sim
